<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="referrer" content="no-referrer"> 
    
    <title><?=$title?> - ExlectrumX Dashboard</title>
    
    <link href="assets/images/favicon.png" rel="shortcut icon" type="image/png">
    
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="assets/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/buttons.bootstrap.min.css" rel="stylesheet"> 
    <!-- JQVMap -->
    <link href="assets/css/jqvmap.min.css" rel="stylesheet">
    <!-- Switchery -->
    <link href="assets/css/switchery.min.css" rel="stylesheet">

    <link href="assets/css/bootstrap-multiselect.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="assets/css/custom.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border-bottom: 1px solid #416182;">
                <a href="index.php" class="site_title"><i class="fa fa-btc fa-lg" style="color:orange"></i> <span>ElectrumX Dash</span></a>
            </div>
            <hr>
            <div class="clearfix"></div>

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <a href="?p=main" <?php if($this->section=="main") echo 'class="active"'; ?>><i class="fa fa-home"></i> Main </a>
                  <a href="?p=sessions" <?php if($this->section=="sessions") echo 'class="active"'; ?>><i class="fa fa-user-o"></i> Sessions </a>
                    <ul class="nav child_menu" style="display: block;">
                      <li <?php if($this->section=="rules") echo 'class="current-page"'; ?>><a href="?p=rules">Rules</a></li>
                      <li <?php if($this->section=="hoster") echo 'class="active"'; ?>><a href="?p=hoster">Hoster</a></li>
                    </ul>                  
                  <a href="?p=peers" <?php if($this->section=="peers") echo 'class="active"'; ?>><i class="fa fa-server"></i> Peers </a>
                  <a href="?p=about" <?php if($this->section=="about") echo 'class="active"'; ?>><i class="fa fa-info"></i> About </a>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- page content -->
        <div class="right_col" role="main" style="min-height:100%;">